apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      labels:
        app: appserver
    spec:
      containers:
      - name: appserver
        image: au.icr.io/nutrition-project-ap/appserver2:latest
---
apiVersion: v1
kind: Service
metadata:  
  name: my-nodeport-service
spec:
  selector:    
    app: appserver
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP